jenkins:
  systemMessage: "Jenkins Job Setup"

unclassified:
  location:
    url: "https://jenkins.csyeteam03.xyz"

jobs:
  - file: "/usr/local/credentials.groovy"
  - file: "/usr/local/tf-validate-seed-job.groovy"
  - file: "/usr/local/static-site-publish-seed-job.groovy"
  - file: "/usr/local/webapp-publish-seed-job.groovy"
  - file: "/usr/local/db-webapp-publish-seed-job.groovy"
  - file: "/usr/local/commitlint-infra-jenkins.groovy"
  - file: "/usr/local/commitlint-ami-jenkins.groovy"
  - file: "/usr/local/commitlint-tf-gcp-infra.groovy"
  - file: "/usr/local/commitlint-static-site.groovy"
  - file: "/usr/local/commitlint-webapp-hello-world.groovy"
  - file: "/usr/local/commitlint-db-webapp.groovy"
